// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQICS_Api.Model.Context;

namespace SQICS_Api.Migrations
{
    [DbContext(typeof(SQICSContext))]
    [Migration("20220718060041_AddGetSubAssyByCodeSP")]
    partial class AddGetSubAssyByCodeSP
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SQICS_Api.Model.tbl_m_bom", b =>
                {
                    b.Property<int>("fld_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("fld_assyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fld_creatdDate")
                        .HasColumnType("datetime");

                    b.Property<int>("fld_createdBy")
                        .HasColumnType("int");

                    b.Property<int>("fld_pieceId")
                        .HasColumnType("int");

                    b.Property<int>("fld_qty")
                        .HasColumnType("int");

                    b.Property<int?>("fld_updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fld_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("fld_id");

                    b.ToTable("tbl_m_bom");
                });

            modelBuilder.Entity("SQICS_Api.Model.tbl_m_operator", b =>
                {
                    b.Property<int>("fld_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("fld_active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("fld_createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("fld_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("fld_employeeId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("fld_firstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("fld_lastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("fld_middleName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("fld_supplierId")
                        .HasColumnType("int");

                    b.Property<int?>("fld_updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fld_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("fld_id");

                    b.HasIndex(new[] { "fld_employeeId" }, "employeeId_unique")
                        .IsUnique();

                    b.ToTable("tbl_m_operator");
                });

            modelBuilder.Entity("SQICS_Api.Model.tbl_m_operator_assy", b =>
                {
                    b.Property<int>("fld_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("fld_assyId")
                        .HasColumnType("int");

                    b.Property<int>("fld_createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("fld_createdDate")
                        .HasColumnType("datetime");

                    b.Property<int>("fld_operatorId")
                        .HasColumnType("int");

                    b.Property<int?>("fld_updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fld_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("fld_id");

                    b.ToTable("tbl_m_operator_assy");
                });

            modelBuilder.Entity("SQICS_Api.Model.tbl_m_operator_station", b =>
                {
                    b.Property<int>("fld_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("fld_createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("fld_createdDate")
                        .HasColumnType("datetime");

                    b.Property<int>("fld_operatorId")
                        .HasColumnType("int");

                    b.Property<int>("fld_stationId")
                        .HasColumnType("int");

                    b.Property<int?>("fld_updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fld_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("fld_id");

                    b.ToTable("tbl_m_operator_station");
                });

            modelBuilder.Entity("SQICS_Api.Model.tbl_m_part", b =>
                {
                    b.Property<int>("fld_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("fld_active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("fld_createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("fld_createdDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("fld_isAssy")
                        .HasColumnType("bit");

                    b.Property<int?>("fld_most")
                        .HasColumnType("int");

                    b.Property<string>("fld_partCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("fld_partName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("fld_remarks")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("fld_spq")
                        .HasColumnType("int");

                    b.Property<int>("fld_supplierId")
                        .HasColumnType("int");

                    b.Property<int?>("fld_updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fld_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("fld_id");

                    b.HasIndex(new[] { "fld_partCode" }, "partCode_unique")
                        .IsUnique();

                    b.ToTable("tbl_m_parts");
                });

            modelBuilder.Entity("SQICS_Api.Model.tbl_t_assy_defect", b =>
                {
                    b.Property<int>("fld_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("fld_createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("fld_createdDate")
                        .HasColumnType("datetime");

                    b.Property<int>("fld_defectId")
                        .HasColumnType("int");

                    b.Property<int>("fld_qty")
                        .HasColumnType("int");

                    b.Property<int>("fld_transactionId")
                        .HasColumnType("int");

                    b.Property<int?>("fld_updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fld_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("fld_id");

                    b.ToTable("tbl_t_assy_defects");
                });

            modelBuilder.Entity("SQICS_Api.Model.tbl_t_lot_label", b =>
                {
                    b.Property<int>("fld_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("fld_createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("fld_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("fld_lotNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("fld_modelId")
                        .HasColumnType("int");

                    b.Property<string>("fld_modelName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("fld_partCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("fld_partName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("fld_printed")
                        .HasColumnType("bit");

                    b.Property<int>("fld_qty")
                        .HasColumnType("int");

                    b.Property<string>("fld_referenceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("fld_remarks")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("fld_reprinted")
                        .HasColumnType("bit");

                    b.Property<int>("fld_transactionId")
                        .HasColumnType("int");

                    b.Property<int?>("fld_updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fld_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("fld_id");

                    b.ToTable("tbl_t_lot_label");
                });

            modelBuilder.Entity("SQICS_Api.Model.tbl_t_transaction", b =>
                {
                    b.Property<int>("fld_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ETimeCompletion")
                        .HasColumnType("datetime");

                    b.Property<int>("fld_assyId")
                        .HasColumnType("int");

                    b.Property<int>("fld_createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("fld_createdDate")
                        .HasColumnType("datetime");

                    b.Property<int>("fld_lineId")
                        .HasColumnType("int");

                    b.Property<bool?>("fld_printFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("fld_qty")
                        .HasColumnType("int");

                    b.Property<int>("fld_supplierId")
                        .HasColumnType("int");

                    b.Property<int>("fld_transactionNo")
                        .HasColumnType("int");

                    b.Property<int?>("fld_updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fld_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("fld_id");

                    b.ToTable("tbl_t_transactions");
                });

            modelBuilder.Entity("SQICS_Api.Model.tbl_t_transaction_detail", b =>
                {
                    b.Property<int>("fld_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("fld_createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("fld_createdDate")
                        .HasColumnType("datetime");

                    b.Property<string>("fld_employeeId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<bool>("fld_judgementFlag")
                        .HasColumnType("bit");

                    b.Property<string>("fld_lotNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("fld_operatorFlag")
                        .HasColumnType("bit");

                    b.Property<int>("fld_pieceId")
                        .HasColumnType("int");

                    b.Property<int>("fld_qty")
                        .HasColumnType("int");

                    b.Property<string>("fld_referenceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("fld_stationId")
                        .HasColumnType("int");

                    b.Property<int>("fld_transactionId")
                        .HasColumnType("int");

                    b.Property<int?>("fld_updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fld_updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("fld_id");

                    b.ToTable("tbl_t_transaction_details");
                });
#pragma warning restore 612, 618
        }
    }
}
